#! /bin/bash 

if [  -n "$(pgrep -f  RGPIOServer)"  ]
then
echo RGPIO server is running, kill it first. Exiting...
exit
fi

if  [ "$1" = "nolog" ] ; then

 java -cp /home/pi/git/RGPIOServer/RGPIOServer.jar:/home/pi/git/RGPIO/lib/'*' rgpioserver/RGPIOServer

else

 loglink=/home/pi/RGPIO/logs/RGPIOlogfile
 logfile=/home/pi/RGPIO/logs/log-`date +%d-%m@%H:%M`
 [ -f $loglink ] && rm $loglink
 touch $logfile
 ln -s $logfile $loglink

 (
 cd /home/pi/git/RGPIO/run
 java -cp /home/pi/git/RGPIOServer/RGPIOServer.jar:/home/pi/git/RGPIO/lib/'*' rgpioserver/RGPIOServer
 )  >> $loglink 2>&1 &

fi
